services:
  nats:
    image: nats:alpine
    command: [ "--js", "--sd", "/data" ]
    ports:
      - "4222:4222" # Client Connections
      - "8222:8222" # HTTP Monitoring
    volumes:
      - nats-data:/data

  engine-server:
    image: ghcr.io/maatini/bpmninja/engine-server:latest
    # build:
    #   context: .
    #   dockerfile: engine-server/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

volumes:
  nats-data:
