use std::time::Duration;

use quick_xml::de::from_str;
use serde::Deserialize;

use engine_core::error::{EngineError, EngineResult};
use engine_core::model::{BpmnElement, ProcessDefinition, ProcessDefinitionBuilder};

#[derive(Debug, Deserialize)]
struct BpmnDefinitions {
    #[allow(dead_code)]
    #[serde(rename = "@id")]
    id: String,
    process: BpmnProcess,
}

#[derive(Debug, Deserialize)]
struct BpmnProcess {
    #[serde(rename = "@id")]
    id: String,
    
    #[serde(rename = "startEvent", default)]
    start_events: Vec<BpmnStartEvent>,
    
    #[serde(rename = "endEvent", default)]
    end_events: Vec<BpmnEndEvent>,
    
    #[serde(rename = "serviceTask", default)]
    service_tasks: Vec<BpmnServiceTask>,
    
    #[serde(rename = "userTask", default)]
    user_tasks: Vec<BpmnUserTask>,
    
    #[serde(rename = "sequenceFlow", default)]
    sequence_flows: Vec<BpmnSequenceFlow>,

    // --- Additional element types generated by bpmn-js ---

    /// Generic `<task>` elements (bpmn-js default when adding a task).
    #[serde(rename = "task", default)]
    generic_tasks: Vec<BpmnGenericTask>,

    /// Script, send, receive, manual, businessRule tasks — all map to ServiceTask.
    #[serde(rename = "scriptTask", default)]
    script_tasks: Vec<BpmnGenericTask>,
    #[serde(rename = "sendTask", default)]
    send_tasks: Vec<BpmnGenericTask>,
    #[serde(rename = "receiveTask", default)]
    receive_tasks: Vec<BpmnGenericTask>,
    #[serde(rename = "manualTask", default)]
    manual_tasks: Vec<BpmnGenericTask>,
    #[serde(rename = "businessRuleTask", default)]
    business_rule_tasks: Vec<BpmnGenericTask>,
    #[serde(rename = "callActivity", default)]
    call_activities: Vec<BpmnGenericTask>,

    /// Gateways — treated as pass-through nodes for now.
    #[serde(rename = "exclusiveGateway", default)]
    exclusive_gateways: Vec<BpmnGenericTask>,
    #[serde(rename = "parallelGateway", default)]
    parallel_gateways: Vec<BpmnGenericTask>,
    #[serde(rename = "inclusiveGateway", default)]
    inclusive_gateways: Vec<BpmnGenericTask>,

    /// Intermediate events — treated as pass-through nodes.
    #[serde(rename = "intermediateThrowEvent", default)]
    intermediate_throw_events: Vec<BpmnGenericTask>,
    #[serde(rename = "intermediateCatchEvent", default)]
    intermediate_catch_events: Vec<BpmnGenericTask>,
}

#[derive(Debug, Deserialize)]
struct BpmnStartEvent {
    #[serde(rename = "@id")]
    id: String,
    #[serde(rename = "timerEventDefinition")]
    timer_event_definition: Option<BpmnTimerEventDefinition>,
}

#[derive(Debug, Deserialize)]
struct BpmnTimerEventDefinition {
    #[serde(rename = "timeDuration")]
    time_duration: Option<String>,
}

#[derive(Debug, Deserialize)]
struct BpmnEndEvent {
    #[serde(rename = "@id")]
    id: String,
}

#[derive(Debug, Deserialize)]
struct BpmnServiceTask {
    #[serde(rename = "@id")]
    id: String,
    #[serde(rename = "@data-handler")]
    handler: Option<String>,
    /// Maatini type attribute: "external" means external task.
    #[serde(rename = "@maatini:type")]
    maatini_type: Option<String>,
    /// Topic name for external tasks.
    #[serde(rename = "@data-topic")]
    topic: Option<String>,
}

#[derive(Debug, Deserialize)]
struct BpmnUserTask {
    #[serde(rename = "@id")]
    id: String,
    #[serde(rename = "@data-assignee")]
    assignee: Option<String>,
}

#[derive(Debug, Deserialize)]
struct BpmnConditionExpression {
    #[serde(rename = "$value")]
    value: String,
}

#[derive(Debug, Deserialize)]
struct BpmnSequenceFlow {
    #[serde(rename = "@id")]
    _id: String,
    #[serde(rename = "@sourceRef")]
    source_ref: String,
    #[serde(rename = "@targetRef")]
    target_ref: String,
    #[serde(rename = "conditionExpression")]
    condition_expression: Option<BpmnConditionExpression>,
}

/// Generic catch-all for BPMN elements we parse but only need the ID from.
#[derive(Debug, Deserialize)]
struct BpmnGenericTask {
    #[serde(rename = "@id")]
    id: String,
    /// Optional name attribute (bpmn-js sometimes sets this).
    #[serde(rename = "@name", default)]
    name: Option<String>,
}

/// Parses a subset of BPMN 2.0 XML and builds a `ProcessDefinition`.
///
/// Note: Since `quick-xml` expects exact structure, the parsed XML must match
/// the structs above (elements rather than attributes where specified, etc.).
pub fn parse_bpmn_xml(xml: &str) -> EngineResult<ProcessDefinition> {
    let defs: BpmnDefinitions = from_str(xml).map_err(|e| {
        EngineError::InvalidDefinition(format!("Failed to parse BPMN XML: {}", e))
    })?;

    let process_id = defs.process.id.clone();
    let mut builder = ProcessDefinitionBuilder::new(process_id);

    // 1. Process Start Events
    for start in defs.process.start_events {
        if let Some(timer) = start.timer_event_definition {
            // Parse duration from PTnHnS
            // Very basic implementation: just looking for "PT{secs}S"
            let dur = if let Some(time) = timer.time_duration {
                let text = time.replace("PT", "").replace("S", "");
                let secs: u64 = text.parse().unwrap_or(0);
                Duration::from_secs(secs)
            } else {
                Duration::from_secs(0)
            };
            builder = builder.node(start.id, BpmnElement::TimerStartEvent(dur));
        } else {
            builder = builder.node(start.id, BpmnElement::StartEvent);
        }
    }

    // 2. Process End Events
    for end in defs.process.end_events {
        builder = builder.node(end.id, BpmnElement::EndEvent);
    }

    // 3. Process Service Tasks (may be external)
    for task in defs.process.service_tasks {
        let is_external = task.maatini_type.as_deref() == Some("external")
            || task.topic.is_some();

        if is_external {
            let topic = task.topic.unwrap_or_else(|| "default".into());
            builder = builder.node(task.id, BpmnElement::ExternalTask { topic });
        } else {
            let handler = task.handler.unwrap_or_else(|| "default_handler".into());
            builder = builder.node(task.id, BpmnElement::ServiceTask(handler));
        }
    }

    // 4. Process User Tasks
    for task in defs.process.user_tasks {
        let assignee = task.assignee.unwrap_or_else(|| "unassigned".into());
        builder = builder.node(task.id, BpmnElement::UserTask(assignee));
    }

    // 5. Generic tasks (bpmn-js default task element)
    //    Also covers scriptTask, sendTask, receiveTask, manualTask,
    //    businessRuleTask, and callActivity — all map to ServiceTask.
    let all_generic_tasks = defs.process.generic_tasks.into_iter()
        .chain(defs.process.script_tasks)
        .chain(defs.process.send_tasks)
        .chain(defs.process.receive_tasks)
        .chain(defs.process.manual_tasks)
        .chain(defs.process.business_rule_tasks)
        .chain(defs.process.call_activities);

    for task in all_generic_tasks {
        let handler = task.name.unwrap_or_else(|| "default_handler".into());
        builder = builder.node(task.id, BpmnElement::ServiceTask(handler));
    }

    // 6. Gateways — treated as pass-through ServiceTask nodes for now.
    let all_gateways = defs.process.exclusive_gateways.into_iter()
        .chain(defs.process.parallel_gateways)
        .chain(defs.process.inclusive_gateways);

    for gw in all_gateways {
        builder = builder.node(gw.id, BpmnElement::ServiceTask("gateway_passthrough".into()));
    }

    // 7. Intermediate events — treated as pass-through nodes.
    let all_intermediate = defs.process.intermediate_throw_events.into_iter()
        .chain(defs.process.intermediate_catch_events);

    for evt in all_intermediate {
        builder = builder.node(evt.id, BpmnElement::ServiceTask("event_passthrough".into()));
    }

    // 8. Process Sequence Flows
    for flow in defs.process.sequence_flows {
        if let Some(cond) = flow.condition_expression {
            builder = builder.conditional_flow(flow.source_ref, flow.target_ref, cond.value.trim());
        } else {
            builder = builder.flow(flow.source_ref, flow.target_ref);
        }
    }

    builder.build()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_simple_bpmn() {
        let xml = r#"
            <bpmn:definitions id="def1" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL">
                <process id="proc1">
                    <startEvent id="start1" />
                    <serviceTask id="svc1" data-handler="my_handler" />
                    <userTask id="ut1" data-assignee="alice" />
                    <endEvent id="end1" />
                    <sequenceFlow id="f1" sourceRef="start1" targetRef="svc1" />
                    <sequenceFlow id="f2" sourceRef="svc1" targetRef="ut1" />
                    <sequenceFlow id="f3" sourceRef="ut1" targetRef="end1" />
                </process>
            </bpmn:definitions>
        "#;

        let def = parse_bpmn_xml(xml).unwrap();
        assert_eq!(def.id, "proc1");
        assert!(def.nodes.contains_key("start1"));
        assert!(def.nodes.contains_key("svc1"));
        assert!(def.nodes.contains_key("ut1"));
        assert!(def.nodes.contains_key("end1"));
        
        assert_eq!(def.next_node("start1"), Some("svc1"));
        assert_eq!(def.next_node("svc1"), Some("ut1"));
        assert_eq!(def.next_node("ut1"), Some("end1"));
        
        match def.nodes.get("svc1").unwrap() {
            BpmnElement::ServiceTask(h) => assert_eq!(h, "my_handler"),
            _ => panic!("Expected ServiceTask"),
        }
        
        match def.nodes.get("ut1").unwrap() {
            BpmnElement::UserTask(a) => assert_eq!(a, "alice"),
            _ => panic!("Expected UserTask"),
        }
    }

    #[test]
    fn parse_conditional_flows() {
        let xml = r#"
            <definitions id="def1" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
                <process id="proc1">
                    <startEvent id="start1" />
                    <exclusiveGateway id="gw1" />
                    <endEvent id="end1" />
                    <endEvent id="end2" />
                    
                    <sequenceFlow id="f1" sourceRef="start1" targetRef="gw1" />
                    
                    <sequenceFlow id="f2" sourceRef="gw1" targetRef="end1">
                        <conditionExpression xsi:type="tFormalExpression">amount &gt; 100</conditionExpression>
                    </sequenceFlow>
                    
                    <sequenceFlow id="f3" sourceRef="gw1" targetRef="end2" />
                </process>
            </definitions>
        "#;

        let def = parse_bpmn_xml(xml).unwrap();
        let flows = def.next_nodes("gw1");
        assert_eq!(flows.len(), 2);
        
        let flow1 = flows.iter().find(|f| f.target == "end1").unwrap();
        assert_eq!(flow1.condition, Some("amount > 100".to_string()));
        
        let flow2 = flows.iter().find(|f| f.target == "end2").unwrap();
        assert_eq!(flow2.condition, None);
    }

    #[test]
    fn parse_timer_start() {
        let xml = r#"
            <definitions id="def1" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
                <process id="proc1">
                    <startEvent id="start1">
                        <timerEventDefinition>
                            <timeDuration>PT60S</timeDuration>
                        </timerEventDefinition>
                    </startEvent>
                    <endEvent id="end1" />
                    <sequenceFlow id="f1" sourceRef="start1" targetRef="end1" />
                </process>
            </definitions>
        "#;

        let def = parse_bpmn_xml(xml).unwrap();
        match def.nodes.get("start1").unwrap() {
            BpmnElement::TimerStartEvent(d) => assert_eq!(d.as_secs(), 60),
            _ => panic!("Expected TimerStartEvent"),
        }
    }

    /// Regression test: bpmn-js generates interleaved elements, e.g.
    /// `startEvent`, `sequenceFlow`, `serviceTask`, `sequenceFlow`, `endEvent`.
    /// quick-xml 0.31 rejected this as "duplicate field `sequenceFlow`".
    /// Fixed by upgrading to quick-xml 0.37 with `overlapped-lists` feature.
    #[test]
    fn parse_interleaved_bpmn_js_output() {
        let xml = r#"
            <bpmn2:definitions id="Definitions_1" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL">
                <bpmn2:process id="Process_1" isExecutable="true">
                    <bpmn2:startEvent id="StartEvent_1" />
                    <bpmn2:sequenceFlow id="Flow_1" sourceRef="StartEvent_1" targetRef="ServiceTask_1" />
                    <bpmn2:serviceTask id="ServiceTask_1" data-handler="validate" />
                    <bpmn2:sequenceFlow id="Flow_2" sourceRef="ServiceTask_1" targetRef="UserTask_1" />
                    <bpmn2:userTask id="UserTask_1" data-assignee="admin" />
                    <bpmn2:sequenceFlow id="Flow_3" sourceRef="UserTask_1" targetRef="EndEvent_1" />
                    <bpmn2:endEvent id="EndEvent_1" />
                </bpmn2:process>
            </bpmn2:definitions>
        "#;

        let def = parse_bpmn_xml(xml).expect("should parse interleaved BPMN XML");
        assert_eq!(def.id, "Process_1");
        assert_eq!(def.nodes.len(), 4);
        assert_eq!(def.flows.len(), 3);
        assert_eq!(def.next_node("StartEvent_1"), Some("ServiceTask_1"));
        assert_eq!(def.next_node("ServiceTask_1"), Some("UserTask_1"));
        assert_eq!(def.next_node("UserTask_1"), Some("EndEvent_1"));
    }
}
